"""Phase 2 Alembic Migration - CRM & Lead Management

Revision ID: 20240114_phase2
Revises: 20240113_phase1
Create: 2024-01-14 00:00:00

This migration creates Phase 2 database tables:
- project_types
- project_subcategories
- requirement_questions
- contacts
- quote_requests
- leads
- activities
- lead_notes
- follow_ups
- attachments

Note: the `activities` table references `quotations.id` and `contracts.id`,
which are created in the Phase 3 migration. Those two foreign keys are added
deferred, inside the Phase 3 migration, using op.create_foreign_key.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20240114_phase2'
down_revision = '20240113_phase1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create project_types table
    op.create_table(
        'project_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_types_name', 'project_types', ['name'], unique=True)
    op.create_index('ix_project_types_slug', 'project_types', ['slug'], unique=True)

    # Create project_subcategories table
    op.create_table(
        'project_subcategories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('project_type_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_subcategories_name', 'project_subcategories', ['name'], unique=True)
    op.create_index('ix_project_subcategories_slug', 'project_subcategories', ['slug'], unique=True)

    # Create requirement_questions table
    op.create_table(
        'requirement_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('field_key', sa.String(), nullable=False),
        sa.Column('field_type', sa.String(), nullable=False),
        sa.Column('is_required', sa.Boolean(), nullable=False),
        sa.Column('options', sa.JSON(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('project_type_id', sa.Integer(), nullable=True),
        sa.Column('subcategory_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
        sa.ForeignKeyConstraint(['subcategory_id'], ['project_subcategories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create contacts table
    op.create_table(
        'contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('whatsapp', sa.String(), nullable=True),
        sa.Column('company_name', sa.String(), nullable=True),
        sa.Column('designation', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=True)

    # Create quote_requests table
    op.create_table(
        'quote_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_number', sa.String(), nullable=False),
        sa.Column('project_type_id', sa.Integer(), nullable=True),
        sa.Column('subcategory_id', sa.Integer(), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('whatsapp', sa.String(), nullable=True),
        sa.Column('company_name', sa.String(), nullable=True),
        sa.Column('designation', sa.String(), nullable=True),
        sa.Column('budget', sa.String(), nullable=True),
        sa.Column('timeline', sa.String(), nullable=True),
        sa.Column('target_audience', sa.Text(), nullable=True),
        sa.Column('existing_system', sa.Text(), nullable=True),
        sa.Column('expected_launch', sa.DateTime(), nullable=True),
        sa.Column('detailed_requirements', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
        sa.ForeignKeyConstraint(['subcategory_id'], ['project_subcategories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_requests_request_number', 'quote_requests', ['request_number'], unique=True)

    # Create leads table
    op.create_table(
        'leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_number', sa.String(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('quote_request_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('project_type_id', sa.Integer(), nullable=True),
        sa.Column('subcategory_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('priority', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('estimated_budget', sa.String(), nullable=True),
        sa.Column('estimated_timeline', sa.String(), nullable=True),
        sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
        sa.Column('qualified_at', sa.DateTime(), nullable=True),
        sa.Column('lost_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
        sa.ForeignKeyConstraint(['subcategory_id'], ['project_subcategories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_lead_number', 'leads', ['lead_number'], unique=True)

    # Create activities table (FKs to quotations/contracts added in Phase 3)
    op.create_table(
        'activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('activity_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('performed_by', sa.Integer(), nullable=True),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('quote_request_id', sa.Integer(), nullable=True),
        sa.Column('quotation_id', sa.Integer(), nullable=True),
        sa.Column('contract_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create lead_notes table
    op.create_table(
        'lead_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('quote_request_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create follow_ups table
    op.create_table(
        'follow_ups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('due_at', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('quote_request_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create attachments table
    op.create_table(
        'attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('storage_key', sa.String(), nullable=False),
        sa.Column('uploaded_by', sa.Integer(), nullable=False),
        sa.Column('related_entity', sa.String(), nullable=False),
        sa.Column('related_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('attachments')
    op.drop_table('follow_ups')
    op.drop_table('lead_notes')
    op.drop_table('activities')
    op.drop_index('ix_leads_lead_number', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_quote_requests_request_number', table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('requirement_questions')
    op.drop_index('ix_project_subcategories_slug', table_name='project_subcategories')
    op.drop_index('ix_project_subcategories_name', table_name='project_subcategories')
    op.drop_table('project_subcategories')
    op.drop_index('ix_project_types_slug', table_name='project_types')
    op.drop_index('ix_project_types_name', table_name='project_types')
    op.drop_table('project_types')
    # ### end Alembic commands ###