"""Phase 3 Alembic Migration - Technical Analysis, Estimation, Quotation, Contract

Revision ID: 20240115_phase3
Revises: 20240114_phase2
Create: 2024-01-15 00:00:00

This migration creates Phase 3 database tables:
- technical_analyses
- estimations
- estimation_items
- quotations
- quotation_items
- quotation_versions
- quotation_comments
- contracts
- contract_activities
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20240115_phase3'
down_revision = '20240114_phase2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create technical_analyses table
    op.create_table(
        'technical_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('prepared_by', sa.Integer(), nullable=True),
        sa.Column('business_requirement', sa.Text(), nullable=True),
        sa.Column('technical_requirement', sa.Text(), nullable=True),
        sa.Column('proposed_solution', sa.Text(), nullable=True),
        sa.Column('architecture_notes', sa.Text(), nullable=True),
        sa.Column('technologies', sa.JSON(), nullable=True),
        sa.Column('integrations', sa.JSON(), nullable=True),
        sa.Column('infrastructure_requirements', sa.JSON(), nullable=True),
        sa.Column('security_requirements', sa.String(), nullable=True),
        sa.Column('assumptions', sa.Text(), nullable=True),
        sa.Column('dependencies', sa.JSON(), nullable=True),
        sa.Column('risks', sa.JSON(), nullable=True),
        sa.Column('constraints', sa.JSON(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('reviewed_by', sa.Integer(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_technical_analyses_lead_id', 'technical_analyses', ['lead_id'], unique=False)

    # Create estimations table
    op.create_table(
        'estimations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'),
        sa.Column('prepared_by', sa.Integer(), nullable=True),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('assumptions', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimations_lead_id', 'estimations', ['lead_id'], unique=False)

    # Create estimation_items table
    op.create_table(
        'estimation_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('estimation_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('discount', sa.Numeric(precision=12, scale=2), default=0, nullable=False),
        sa.Column('tax', sa.Numeric(precision=12, scale=2), default=0, nullable=False),
        sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('display_order', sa.Integer(), default=0, nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['estimation_id'], ['estimations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimation_items_estimation_id', 'estimation_items', ['estimation_id'], unique=False)

    # Create quotations table
    op.create_table(
        'quotations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quotation_number', sa.String(), unique=True, nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False, server_default='1'),
        sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'),
        sa.Column('currency', sa.String(), nullable=False, server_default='USD'),
        sa.Column('subtotal', sa.Numeric(precision=14, scale=2), default=0, nullable=False),
        sa.Column('discount_type', sa.String(), nullable=False, server_default='percentage'),
        sa.Column('discount', sa.Numeric(precision=14, scale=2), default=0, nullable=False),
        sa.Column('tax', sa.Numeric(precision=14, scale=2), default=0, nullable=False),
        sa.Column('total', sa.Numeric(precision=14, scale=2), default=0, nullable=False),
        sa.Column('validity_days', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('valid_until', sa.DateTime(), nullable=True),
        sa.Column('estimated_timeline', sa.String(), nullable=True),
        sa.Column('payment_terms', sa.Text(), nullable=True),
        sa.Column('terms_and_conditions', sa.Text(), nullable=True),
        sa.Column('customer_message', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('viewed_at', sa.DateTime(), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('rejected_at', sa.DateTime(), nullable=True),
        sa.Column('quotation_version_reference', sa.String(), nullable=True),
        sa.Column('previous_version', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotations_lead_id', 'quotations', ['lead_id'], unique=False)
    op.create_index('ix_quotations_valid_until', 'quotations', ['valid_until'], unique=False)

    # Create quotation_items table
    op.create_table(
        'quotation_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quotation_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('discount', sa.Numeric(precision=12, scale=2), default=0, nullable=False),
        sa.Column('tax', sa.Numeric(precision=12, scale=2), default=0, nullable=False),
        sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('display_order', sa.Integer(), default=0, nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotation_items_quotation_id', 'quotation_items', ['quotation_id'], unique=False)

    # Create quotation_versions table
    op.create_table(
        'quotation_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quotation_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'),
        sa.Column('effective_from', sa.DateTime(), nullable=False),
        sa.Column('effective_until', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotation_versions_quotation_id', 'quotation_versions', ['quotation_id'], unique=False)

    # Create quotation_comments table
    op.create_table(
        'quotation_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quotation_id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_internal', sa.Boolean(), default=True, nullable=False),
        sa.Column('parent_comment_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create contracts table
    op.create_table(
        'contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contract_number', sa.String(), unique=True, nullable=False),
        sa.Column('quotation_id', sa.Integer(), nullable=True),
        sa.Column('quotation_version', sa.String(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('scope', sa.Text(), nullable=True),
        sa.Column('deliverables', sa.Text(), nullable=True),
        sa.Column('payment_terms', sa.Text(), nullable=True),
        sa.Column('terms_and_conditions', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('expired_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracts_lead_id', 'contracts', ['lead_id'], unique=False)
    op.create_index('ix_contracts_quotation_id', 'contracts', ['quotation_id'], unique=False)

    # Create contract_activities table
    op.create_table(
        'contract_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contract_id', sa.Integer(), nullable=False),
        sa.Column('activity_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('performed_by', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_activities_contract_id', 'contract_activities', ['contract_id'], unique=False)

    # Deferred foreign keys for activities (created in Phase 2), referencing Phase 3 tables
    op.create_foreign_key('fk_activities_quotation_id', 'activities', 'quotations', ['quotation_id'], ['id'])
    op.create_foreign_key('fk_activities_contract_id', 'activities', 'contracts', ['contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('fk_activities_contract_id', 'activities', type_='foreignkey')
    op.drop_constraint('fk_activities_quotation_id', 'activities', type_='foreignkey')

    op.drop_table('contract_activities')
    op.drop_index('ix_contract_activities_contract_id', table_name='contract_activities')
    op.drop_table('contracts')
    op.drop_index('ix_contracts_quotation_id', table_name='contracts')
    op.drop_index('ix_contracts_lead_id', table_name='contracts')
    op.drop_table('quotation_comments')
    op.drop_table('quotation_versions')
    op.drop_index('ix_quotation_versions_quotation_id', table_name='quotation_versions')
    op.drop_table('quotation_items')
    op.drop_index('ix_quotation_items_quotation_id', table_name='quotation_items')
    op.drop_table('quotations')
    op.drop_index('ix_quotations_valid_until', table_name='quotations')
    op.drop_index('ix_quotations_lead_id', table_name='quotations')
    op.drop_table('estimation_items')
    op.drop_index('ix_estimation_items_estimation_id', table_name='estimation_items')
    op.drop_table('estimations')
    op.drop_index('ix_estimations_lead_id', table_name='estimations')
    op.drop_table('technical_analyses')
    op.drop_index('ix_technical_analyses_lead_id', table_name='technical_analyses')
    # ### end Alembic commands ###